#!/usr/bin/python2

import random
import subprocess
import os
import argparse
from time import sleep as stop

parser = argparse.ArgumentParser()

parser.add_argument('-folder', type=str)
parser.add_argument('--cont', action='store_true')
parser.add_argument('-timeout', type=int)

results = parser.parse_args()

try:
    files = os.listdir(results.folder)
    random.shuffle(files)
except TypeError:
    print 'Usage is:\n\t wallpaperchanger -folder "dirname" optional -cont'
    exit()

if all([results.cont, results.timeout]):
    while 1:
        bkgd = os.path.join(results.folder, random.choice(files))
        subprocess.Popen(['feh', '--bg-scale', bkgd])
        stop(results.timeout * 60)


if results.folder:
    bkgd = os.path.join(results.folder, random.choice(files))
    subprocess.Popen(['feh', '--bg-scale', bkgd])
    
else:
    print 'Usage is:\n\t wallpaperchanger -folder "dirname" optional -cont'
    


